package com.bishe.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer id;


    private Integer workAge;

    public Integer getWorkAge() {
        return workAge;
    }

    public void setWorkAge(Integer workAge) {
        this.workAge = workAge;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.tel
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mark
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.tel
     *
     * @return the value of employee.tel
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.tel
     *
     * @param tel the value for employee.tel
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.time
     *
     * @return the value of employee.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.time
     *
     * @param time the value for employee.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mark
     *
     * @return the value of employee.mark
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mark
     *
     * @param mark the value for employee.mark
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.logic_del
     *
     * @return the value of employee.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.logic_del
     *
     * @param logicDel the value for employee.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}