package com.bishe.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer logicDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.name
     *
     * @return the value of post.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.name
     *
     * @param name the value for post.name
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.money
     *
     * @return the value of post.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.money
     *
     * @param money the value for post.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.logic_del
     *
     * @return the value of post.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.logic_del
     *
     * @param logicDel the value for post.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.time
     *
     * @return the value of post.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.time
     *
     * @param time the value for post.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}