package com.bishe.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class SalarySheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.e_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.day
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private double day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.p_s_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer pSId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary_sheet.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.id
     *
     * @return the value of salary_sheet.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.id
     *
     * @param id the value for salary_sheet.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.e_id
     *
     * @return the value of salary_sheet.e_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.e_id
     *
     * @param eId the value for salary_sheet.e_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.day
     *
     * @return the value of salary_sheet.day
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public double getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.day
     *
     * @param day the value for salary_sheet.day
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setDay(double day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.money
     *
     * @return the value of salary_sheet.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.money
     *
     * @param money the value for salary_sheet.money
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.p_s_id
     *
     * @return the value of salary_sheet.p_s_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getpSId() {
        return pSId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.p_s_id
     *
     * @param pSId the value for salary_sheet.p_s_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setpSId(Integer pSId) {
        this.pSId = pSId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.time
     *
     * @return the value of salary_sheet.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.time
     *
     * @param time the value for salary_sheet.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary_sheet.logic_del
     *
     * @return the value of salary_sheet.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary_sheet.logic_del
     *
     * @param logicDel the value for salary_sheet.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}