package com.bishe.model.vo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class PayStructureVo {

    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_structure.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_structure.basic
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer basic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_structure.post_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_structure.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_structure.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_structure.id
     *
     * @return the value of pay_structure.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_structure.id
     *
     * @param id the value for pay_structure.id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_structure.basic
     *
     * @return the value of pay_structure.basic
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getBasic() {
        return basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_structure.basic
     *
     * @param basic the value for pay_structure.basic
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setBasic(Integer basic) {
        this.basic = basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_structure.post_id
     *
     * @return the value of pay_structure.post_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_structure.post_id
     *
     * @param postId the value for pay_structure.post_id
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_structure.time
     *
     * @return the value of pay_structure.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_structure.time
     *
     * @param time the value for pay_structure.time
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_structure.logic_del
     *
     * @return the value of pay_structure.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_structure.logic_del
     *
     * @param logicDel the value for pay_structure.logic_del
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}
