package com.salary.dao;

import com.salary.model.Advance;
import java.util.List;

public interface AdvanceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Advance
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Advance
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    int insert(Advance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Advance
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    Advance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Advance
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    List<Advance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Advance
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    int updateByPrimaryKey(Advance record);
}