package com.salary.dao;

import com.salary.model.Employee;
import java.util.List;

public interface EmployeeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    int updateByPrimaryKey(Employee record);
}