package com.salary.dao;

import com.salary.model.PlaceAndEmployee;
import java.util.List;

public interface PlaceAndEmployeeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place_and_Employee
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place_and_Employee
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    int insert(PlaceAndEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place_and_Employee
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    PlaceAndEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place_and_Employee
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    List<PlaceAndEmployee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place_and_Employee
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    int updateByPrimaryKey(PlaceAndEmployee record);
}