package com.salary.dao;

import com.salary.model.Place;
import java.util.List;

public interface PlaceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    int insert(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    Place selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    List<Place> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Place
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    int updateByPrimaryKey(Place record);
}