package com.bishe.dao;

import com.bishe.model.PayStructure;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PayStructureDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_structure
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_structure
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int insert(PayStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_structure
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    PayStructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_structure
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    List<PayStructure> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_structure
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int updateByPrimaryKey(PayStructure record);
}