package com.bishe.dao;

import com.bishe.model.SalarySheet;
import com.bishe.model.vo.SalarySheetVo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SalarySheetDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_sheet
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_sheet
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int insert(SalarySheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_sheet
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    SalarySheet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_sheet
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    List<SalarySheetVo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_sheet
     *
     * @mbg.generated Fri Jan 10 10:54:28 CST 2020
     */
    int updateByPrimaryKey(SalarySheet record);
}