package com.salary.model;

import java.util.Date;

public class Advance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Advance.id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Advance.e_id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Advance.money
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Advance.time
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Advance.logic_del
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Advance.id
     *
     * @return the value of Advance.id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Advance.id
     *
     * @param id the value for Advance.id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Advance.e_id
     *
     * @return the value of Advance.e_id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Advance.e_id
     *
     * @param eId the value for Advance.e_id
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Advance.money
     *
     * @return the value of Advance.money
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Advance.money
     *
     * @param money the value for Advance.money
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Advance.time
     *
     * @return the value of Advance.time
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Advance.time
     *
     * @param time the value for Advance.time
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Advance.logic_del
     *
     * @return the value of Advance.logic_del
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Advance.logic_del
     *
     * @param logicDel the value for Advance.logic_del
     *
     * @mbg.generated Sat Jan 04 10:19:13 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}