package com.salary.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.e_name
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private String eName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.e_day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer eDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.mark
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.id
     *
     * @return the value of Employee.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.id
     *
     * @param id the value for Employee.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.e_name
     *
     * @return the value of Employee.e_name
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.e_name
     *
     * @param eName the value for Employee.e_name
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void seteName(String eName) {
        this.eName = eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.e_day
     *
     * @return the value of Employee.e_day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer geteDay() {
        return eDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.e_day
     *
     * @param eDay the value for Employee.e_day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void seteDay(Integer eDay) {
        this.eDay = eDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.mark
     *
     * @return the value of Employee.mark
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.mark
     *
     * @param mark the value for Employee.mark
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.logic_del
     *
     * @return the value of Employee.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.logic_del
     *
     * @param logicDel the value for Employee.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}