package com.salary.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.id
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.e_name
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private String eName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.e_day
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private Integer eDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.mark
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.logic_del
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private Integer logicDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.time
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.tel
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    private Long tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.id
     *
     * @return the value of Employee.id
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.id
     *
     * @param id the value for Employee.id
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.e_name
     *
     * @return the value of Employee.e_name
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.e_name
     *
     * @param eName the value for Employee.e_name
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void seteName(String eName) {
        this.eName = eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.e_day
     *
     * @return the value of Employee.e_day
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public Integer geteDay() {
        return eDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.e_day
     *
     * @param eDay the value for Employee.e_day
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void seteDay(Integer eDay) {
        this.eDay = eDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.mark
     *
     * @return the value of Employee.mark
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.mark
     *
     * @param mark the value for Employee.mark
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.logic_del
     *
     * @return the value of Employee.logic_del
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.logic_del
     *
     * @param logicDel the value for Employee.logic_del
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.time
     *
     * @return the value of Employee.time
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.time
     *
     * @param time the value for Employee.time
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.tel
     *
     * @return the value of Employee.tel
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public Long getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.tel
     *
     * @param tel the value for Employee.tel
     *
     * @mbg.generated Sat Jan 04 15:13:41 CST 2020
     */
    public void setTel(Long tel) {
        this.tel = tel;
    }
}