package com.salary.model;

public class Place {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.id
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.p_name
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.p_day
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private Integer pDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.mark
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.logic_del
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private Integer logicDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place.p_day_salary
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    private Integer pDaySalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.id
     *
     * @return the value of Place.id
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.id
     *
     * @param id the value for Place.id
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.p_name
     *
     * @return the value of Place.p_name
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.p_name
     *
     * @param pName the value for Place.p_name
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.p_day
     *
     * @return the value of Place.p_day
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public Integer getpDay() {
        return pDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.p_day
     *
     * @param pDay the value for Place.p_day
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setpDay(Integer pDay) {
        this.pDay = pDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.mark
     *
     * @return the value of Place.mark
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.mark
     *
     * @param mark the value for Place.mark
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.logic_del
     *
     * @return the value of Place.logic_del
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.logic_del
     *
     * @param logicDel the value for Place.logic_del
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place.p_day_salary
     *
     * @return the value of Place.p_day_salary
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public Integer getpDaySalary() {
        return pDaySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place.p_day_salary
     *
     * @param pDaySalary the value for Place.p_day_salary
     *
     * @mbg.generated Sat Dec 14 11:41:05 CST 2019
     */
    public void setpDaySalary(Integer pDaySalary) {
        this.pDaySalary = pDaySalary;
    }
}