package com.salary.model;

public class PlaceAndEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.p_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.e_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.day
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.mark
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Place_and_Employee.logic_del
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.id
     *
     * @return the value of Place_and_Employee.id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.id
     *
     * @param id the value for Place_and_Employee.id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.p_id
     *
     * @return the value of Place_and_Employee.p_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.p_id
     *
     * @param pId the value for Place_and_Employee.p_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.e_id
     *
     * @return the value of Place_and_Employee.e_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.e_id
     *
     * @param eId the value for Place_and_Employee.e_id
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.day
     *
     * @return the value of Place_and_Employee.day
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.day
     *
     * @param day the value for Place_and_Employee.day
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.mark
     *
     * @return the value of Place_and_Employee.mark
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.mark
     *
     * @param mark the value for Place_and_Employee.mark
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Place_and_Employee.logic_del
     *
     * @return the value of Place_and_Employee.logic_del
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Place_and_Employee.logic_del
     *
     * @param logicDel the value for Place_and_Employee.logic_del
     *
     * @mbg.generated Thu Dec 19 20:53:46 CST 2019
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}