package com.salary.model;

public class Salary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Salary.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Salary.e_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Salary.p_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Salary.day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Salary.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    private Integer logicDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Salary.id
     *
     * @return the value of Salary.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Salary.id
     *
     * @param id the value for Salary.id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Salary.e_id
     *
     * @return the value of Salary.e_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Salary.e_id
     *
     * @param eId the value for Salary.e_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Salary.p_id
     *
     * @return the value of Salary.p_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Salary.p_id
     *
     * @param pId the value for Salary.p_id
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Salary.day
     *
     * @return the value of Salary.day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Salary.day
     *
     * @param day the value for Salary.day
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Salary.logic_del
     *
     * @return the value of Salary.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public Integer getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Salary.logic_del
     *
     * @param logicDel the value for Salary.logic_del
     *
     * @mbg.generated Sun Dec 15 16:41:20 CST 2019
     */
    public void setLogicDel(Integer logicDel) {
        this.logicDel = logicDel;
    }
}